export const productos = [
    { id: 1, nombre: 'bicicleta elite RIN 29', precio: 1300, cantidad: 59},
    { id: 2, nombre: 'bicicleta epic expert montañera ', precio: 6500, cantidad: 9 },
    { id: 3, nombre: 'bicicleta rockhopper RIN 29', precio: 860, cantidad: 4 },
    { id: 4, nombre: 'bicicleta SPZ LEVO montañera', precio: 7200, cantidad: 20 },
    { id: 5, nombre: 'bicicleta rockhopper RIN 29', precio: 860, cantidad: 39 },
    { id: 6, nombre: 'bicicleta sirrus 3.0 RUTA', precio: 1150, cantidad: 59 },
    { id: 7, nombre: 'bicicleta SPZ diverge RUTA', precio: 1450, cantidad: 9 },
    { id: 8, nombre: 'bicicleta SPZ expert shiv RUTA', precio: 9000, cantidad: 4 },
    { id: 9, nombre: 'bicicleta SPZ sirrus RUTA', precio: 800, cantidad: 20 },
    { id: 10, nombre: 'bicicleta TARMAC RUTA', precio: 5200, cantidad: 39 },
    { id: 11, nombre: 'bicicleta SPZ ELECTRICA E5', precio: 6100, cantidad: 59 },
    { id: 12, nombre: 'bicicleta ROUBAIX COMP', precio: 5200, cantidad: 9 },
    { id: 13, nombre: 'casco propero', precio: 155, cantidad: 4},
    { id: 14, nombre: 'casco TACTIC 3', precio: 95, cantidad: 20 },
    { id: 15, nombre: 'casco TACTIC 4', precio: 110, cantidad: 39 },
    { id: 16, nombre: 'medias NICERIDE AMARILLAS', precio: 10, cantidad: 59 },
    { id: 17, nombre: 'medias UBX CASINO', precio: 10, cantidad: 9 },
    { id: 18, nombre: 'MEDIAS UBX ROYALE', precio: 10, cantidad: 4 },
    { id: 19, nombre: 'zapatillas de ruta ARES', precio: 470, cantidad: 20 },
    { id: 20, nombre: 'zapatillas de ruta ARES RD', precio: 470, cantidad: 39 },
    { id: 21, nombre: 'zapatillas recon ', precio: 120, cantidad: 59 },
    { id: 22, nombre: 'zapatillas recon MTB', precio: 120, cantidad: 9 },
    { id: 23, nombre: 'zapatillas motodiva', precio: 100, cantidad: 4 },
    { id: 24, nombre: 'zapatillas WORKS 6', precio: 195, cantidad: 20 }
]