export const productos = [
    { id: 1, nombre: 'bicicleta elite RIN 29', precio: 1300, cantidad: 59, img: "../imagenes/bici-elite-29.jpeg"},
    { id: 2, nombre: 'bicicleta epic expert montañera ', precio: 6500, cantidad: 9, img: "../imagenes/epic-expert-montañera.jpeg"},
    { id: 3, nombre: 'bicicleta rockhopper RIN 29', precio: 860, cantidad: 4, img:"../imagenes/montañera-29.jpeg" },
    { id: 4, nombre: 'bicicleta SPZ LEVO montañera', precio: 7200, cantidad: 20, img:"../imagenes/montañera-spz-levo.jpeg"},
    { id: 5, nombre: 'bicicleta rockhopper RIN 29', precio: 860, cantidad: 39, img:"../imagenes/rockhopper-29.jpeg" },
    { id: 6, nombre: 'bicicleta sirrus 3.0 RUTA', precio: 1150, cantidad: 59,img:"../imagenes/sirrus-3.0-ruta.jpeg" },
    { id: 7, nombre: 'bicicleta SPZ diverge RUTA', precio: 1450, cantidad: 9,img:"../imagenes/spz-diverge-e5-ruta.jpeg" },
    { id: 8, nombre: 'bicicleta SPZ expert shiv RUTA', precio: 9000, cantidad: 4,img:"../imagenes/spz-shiv-expert-ruta.jpeg" },
    { id: 9, nombre: 'bicicleta SPZ sirrus RUTA', precio: 800, cantidad: 20,img:"../imagenes/spz-sirrus-ruta.jpeg" },
    { id: 10, nombre: 'bicicleta TARMAC RUTA', precio: 5200, cantidad: 39,img:"../imagenes/spz-tarmac-ruta.jpeg" },
    { id: 11, nombre: 'bicicleta SPZ ELECTRICA E5', precio: 6100, cantidad: 59,img:"../imagenes/electrica-spz-creo-E5.jpeg" },
    { id: 12, nombre: 'bicicleta ROUBAIX COMP', precio: 5200, cantidad: 9,img:"../imagenes/bicicleta-roubaix-comp.jpeg" },
    { id: 13, nombre: 'casco propero', precio: 155, cantidad: 4,img:"../imagenes/casco-spz-propero.jpeg"},
    { id: 14, nombre: 'casco TACTIC 3', precio: 95, cantidad: 20, img:"../imagenes/casco-spz-tactic3.jpeg" },
    { id: 15, nombre: 'casco TACTIC 4', precio: 110, cantidad: 39, img:"../imagenes/casco-spz-tactic4.jpeg" },
    { id: 16, nombre: 'medias NICERIDE AMARILLAS', precio: 10, cantidad: 59,img:"../imagenes/media-nice-ride-amarilla.jpeg" },
    { id: 17, nombre: 'medias UBX CASINO', precio: 10, cantidad: 9,img:"../imagenes/media-ubx-casino.jpeg" },
    { id: 18, nombre: 'MEDIAS UBX ROYALE', precio: 10, cantidad: 4, img:"../imagenes/media-ubx-royale.jpeg" },
    { id: 19, nombre: 'zapatillas de ruta ARES', precio: 470, cantidad: 20, img:"../imagenes/zapatilla-ruta-ares.jpeg" },
    { id: 20, nombre: 'zapatillas de ruta ARES RD', precio: 470, cantidad: 39, img:"../imagenes/zapatilla-ruta-ares-rd.jpeg" },
    { id: 21, nombre: 'zapatillas recon ', precio: 120, cantidad: 59,img:"../imagenes/zapatilla-recon.jpeg" },
    { id: 22, nombre: 'zapatillas recon MTB', precio: 120, cantidad: 9, img:"../imagenes/zapatilla-recon-mtb.jpeg" },
    { id: 23, nombre: 'zapatillas motodiva', precio: 100, cantidad: 4, img:"../imagenes/zapatilla-motodiva.jpeg" },
    { id: 24, nombre: 'zapatillas WORKS 6', precio: 195, cantidad: 20,img:"../imagenes/zapatilla-works6.jpeg" }
]